name: Publish to Docker Hub

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Available QEMU platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_ID=${{ secrets.DOCKERHUB_USER }}/deluge_exporter

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          TAG_ARGS=(--tag "${IMAGE_ID}:${VERSION}")

          # For a new version X.Y.Z, create tags for X.Y.Z, X.Y and X
          if [ "${VERSION}" != "latest" ]; then
            MINOR_VERSION="${VERSION%.*}"
            if [ "${MINOR_VERSION}" != "$VERSION" ]; then # VERSION is either X.Y or X.Y.Z
              TAG_ARGS+=(--tag "${IMAGE_ID}:${MINOR_VERSION}")
              MAJOR_VERSION="${MINOR_VERSION%.*}"
              if [ "${MAJOR_VERSION}" != "${MINOR_VERSION}" ]; then # VERSION is X.Y.Z
                TAG_ARGS+=(--tag "${IMAGE_ID}:${MAJOR_VERSION}")
              fi
            fi
          fi

          echo "IMAGE_ID=$IMAGE_ID"
          echo "TAGS=${TAG_ARGS[*]}"

          docker buildx build \
            --push \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            "${TAG_ARGS[@]}" \
            .
